package com.myspace.solicitacao_ferias;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Aprovacao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean aprovado;
	private java.lang.String comentario;

	public Aprovacao() {
	}

	public java.lang.Boolean getAprovado() {
		return this.aprovado;
	}

	public void setAprovado(java.lang.Boolean aprovado) {
		this.aprovado = aprovado;
	}

	public java.lang.String getComentario() {
		return this.comentario;
	}

	public void setComentario(java.lang.String comentario) {
		this.comentario = comentario;
	}

	public Aprovacao(java.lang.Boolean aprovado, java.lang.String comentario) {
		this.aprovado = aprovado;
		this.comentario = comentario;
	}

}