package com.myspace.solicitacao_ferias;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AprovacaoChefia implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AprovacaoChefia() {
    }




}